# Inside this file is the configuration options
# for the data sources that SWM supports
worldConfig:
  source: file
  spawn: 0.2, 255, 0.2
  difficulty: peaceful
  allowMonsters: true
  allowAnimals: true
  dragonBattle: false
  pvp: true
  environment: NORMAL
  worldType: DEFAULT
  defaultBiome: minecraft:plains
  loadOnStartup: false
  loadOnWarp: false
  readOnly: false
datasourcesConfig:
  file:
    path: slime_worlds
  mysql:
    enabled: false
    host: 127.0.0.1
    port: 3306
    username: slimeworldmanager
    password: ''
    database: slimeworldmanager
    usessl: false
    sqlUrl: jdbc:mysql://{host}:{port}/{database}?autoReconnect=true&allowMultiQueries=true&useSSL={usessl}
  mongodb:
    enabled: false
    host: 127.0.0.1
    port: 27017
    auth: admin
    username: slimeworldmanager
    password: ''
    database: slimeworldmanager
    collection: worlds
    uri: ''
  redis:
    enabled: false
    uri: redis://{password}@{host}:{port}/0
